### ISSUE TITLE
Error: Protocol error (Page.navigate): Invalid parameters url: string value expected

### ISSUE THREAD

**Issue by fn5** [spieglt/fb-delete#10]
Hello - I try and just do the following and I get this error. Chromium stays open and stuck at:

https://mbasic.facebook.com/[PROFILE_USERNAME]?ref_component=mbasic_home_header&ref_page=%2Fwap%2Fhome.php&refid=8

```
? Please enter your Facebook password: *****************
? Select the categories you'd like to delete: Posts
? Select the years you'd like to delete: 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2
005, 2004
(node:15252) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Invalid parameters url: string value expected
    at C:\Users\jack\Downloads\fb-delete\node_modules\puppeteer\lib\Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\jack\Downloads\fb-delete\node_modules\puppeteer\lib\Connection.js:182:12)
    at navigate (C:\Users\jack\Downloads\fb-delete\node_modules\puppeteer\lib\FrameManager.js:118:39)
    at FrameManager.navigateFrame (C:\Users\jack\Downloads\fb-delete\node_modules\puppeteer\lib\FrameManager.js:95:7)
    at Frame.goto (C:\Users\jack\Downloads\fb-delete\node_modules\puppeteer\lib\FrameManager.js:406:37)
    at Frame.<anonymous> (C:\Users\jack\Downloads\fb-delete\node_modules\puppeteer\lib\helper.js:112:23)
    at Page.goto (C:\Users\jack\Downloads\fb-delete\node_modules\puppeteer\lib\Page.js:674:49)
    at Page.<anonymous> (C:\Users\jack\Downloads\fb-delete\node_modules\puppeteer\lib\helper.js:112:23)
    at followLinkByContent (C:\Users\jack\Downloads\fb-delete\index.js:101:14)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\jack\Downloads\fb-delete\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (C:\Users\jack\Downloads\fb-delete\node_modules\puppeteer\lib\Page.js:674:49)
    at Page.<anonymous> (C:\Users\jack\Downloads\fb-delete\node_modules\puppeteer\lib\helper.js:112:23)
    at followLinkByContent (C:\Users\jack\Downloads\fb-delete\index.js:101:14)
    at async next (C:\Users\jack\Downloads\fb-delete\index.js:30:3)
    at async main (C:\Users\jack\Downloads\fb-delete\index.js:25:3)
(node:15252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by spieglt** [comment]
Hmm, so seems like it's getting stuck trying to find the Activity Log. Unfortunately I don't have an account any more so can't test.

Edit: missed the link you put at the top. I'm not sure why it wouldn't find the Activity Log,

**Comment by fn5** [comment]
I fixed it with the following code. If I work out how to fix it without relation to my specific profile I'll post here.

...
```
await page.goto('https://mbasic.facebook.com/[PROFILE_USERNAME]/allactivity');

  await next(answers.categories, answers.years);
}

async function next(categories, years) {
  //await followLinkByContent('Profile');
  //await followLinkByContent('Activity Log');
  await followLinkByContent('Filter');
```
...

**Comment by spieglt** [comment]
Awesome, thanks!

**Comment by bwalchen** [comment]
Running into the same error as above. Curious if you were able to find a solution to this

**Comment by spieglt** [comment]
@bwalchen @jackitsdotcom This should be fixed in the latest commit, please let me know if you try. Thanks.

**Comment by vdeville** [comment]
Hello
Same error here, i'm on master.
Thanks

**Comment by vdeville** [comment]
Fixed, you need to set your account language in English

**Comment by linuxindo** [comment]
> Fixed, you need to set your account language in English

fixed thx  change to English (US)
UK its dont work

**Comment by spieglt** [comment]
Thanks, added a note to the readme.
