### ISSUE TITLE
error

### ISSUE THREAD

**Issue by BlazeVertex** [spieglt/fb-delete#19]
Error: Error: failed to find element matching selector "input[id=m_login_email]"
    at ElementHandle.$eval (C:\Users\Mr.Fox\Downloads\Compressed\fb-delete-master\fb-delete-master\node_modules\puppeteer\lib\JSHandle.js:504:13)
    at async main (C:\Users\Mr.Fox\Downloads\Compressed\fb-delete-master\fb-delete-master\index.js:18:3)
  -- ASYNC --
    at ElementHandle.<anonymous> (C:\Users\Mr.Fox\Downloads\Compressed\fb-delete-master\fb-delete-master\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.$eval (C:\Users\Mr.Fox\Downloads\Compressed\fb-delete-master\fb-delete-master\node_modules\puppeteer\lib\DOMWorld.js:156:21)
    at async main (C:\Users\Mr.Fox\Downloads\Compressed\fb-delete-master\fb-delete-master\index.js:18:3)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Mr.Fox\Downloads\Compressed\fb-delete-master\fb-delete-master\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.$eval (C:\Users\Mr.Fox\Downloads\Compressed\fb-delete-master\fb-delete-master\node_modules\puppeteer\lib\Page.js:345:29)
    at Page.<anonymous> (C:\Users\Mr.Fox\Downloads\Compressed\fb-delete-master\fb-delete-master\node_modules\puppeteer\lib\helper.js:112:23)
    at main (C:\Users\Mr.Fox\Downloads\Compressed\fb-delete-master\fb-delete-master\index.js:18:14)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)

**Comment by spieglt** [comment]
I'm not sure what happened here. Is your browser set to use English? Any other context or details you can provide?

**Comment by spieglt** [comment]
Closing as I never heard back
