### ISSUE TITLE
After entering the user name and password ( double checked for correctness, clipboard correctness as well), I get the error( exception) 

### ISSUE THREAD

**Issue by raikrahul** [spieglt/fb-delete#2]
```
(node:1465) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!

(chrome:1475): Gtk-WARNING **: 13:29:45.860: cannot open display:


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/trou                                          bleshooting.md

    at onClose (/home/..[someLocation]/Launcher.js:255:14)
    at Interface.helper.addEventListener (/home/k/Downloads/fb-delete-master/nod                                          e_modules/puppeteer/lib/Launcher.js:244:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at Socket.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
(node:1465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This                                           error originated either by throwing inside of an async function without a catch                                           block, or by rejecting a promise which was not handled with .catch(). (rejection                                           id: 1)
(node:1465) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre                                          cated. In the future, promise rejections that are not handled will terminate the                                           Node.js process with a non-zero exit code.
```

**Comment by RonaldJerez** [comment]
Do you have two step authentication enabled? I also had a problem at this step, i don't remember what the exact error was but i noticed it was because of two step authentication, I disabled it and tried again and it worked fine.

**Comment by spieglt** [comment]
@raikrahul Hey, sorry about this. I don't know why I never got notifications about the issues for this repo but I'm just now seeing them. @RonaldJerez's comment is correct, this code does not handle 2FA at all so I'd recommend disabling it, running this script, and re-enabling it. However, it looks like you weren't able to open Chrome at all? Were you on Linux?
