### ISSUE TITLE
Accept Cookies

### ISSUE THREAD

**Issue by jakobjn** [spieglt/fb-delete#21]
Upon running the script as instructed, a chromium windows opens very briefly. Following error is printed in the terminal.

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Error: failed to find element matching selector "input[id=m_login_email]"
    at ElementHandle.$eval (/home/jakob/Downloads/fb-delete/node_modules/puppeteer/lib/JSHandle.js:504:13)
    at async main (/home/jakob/Downloads/fb-delete/index.js:18:3)
  -- ASYNC --
    at ElementHandle.<anonymous> (/home/jakob/Downloads/fb-delete/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.$eval (/home/jakob/Downloads/fb-delete/node_modules/puppeteer/lib/DOMWorld.js:156:21)
    at async main (/home/jakob/Downloads/fb-delete/index.js:18:3)
  -- ASYNC --
    at Frame.<anonymous> (/home/jakob/Downloads/fb-delete/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.$eval (/home/jakob/Downloads/fb-delete/node_modules/puppeteer/lib/Page.js:345:29)
    at Page.<anonymous> (/home/jakob/Downloads/fb-delete/node_modules/puppeteer/lib/helper.js:112:23)
    at main (/home/jakob/Downloads/fb-delete/index.js:18:14)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)

After recording the screen for the script execution, it seems that an 'accept cookies' window is what opens. It seems like the chromium browser that's opened is one installed as a dependency.

**Comment by spieglt** [comment]
That's strange, I'm not seeing the "accept cookies" window when I visit mbasic.facebook.com in a fresh browser. Would it possible to send a screenshot? That copy of Chromium is included by Puppeteer.

**Comment by opc241** [comment]
Executing the script in my computer results to the same behaviour descriped by the TO. 
But the temporary opened chromium browser will exit before i could manually click on "accept cookies"

> , I'm not seeing the "accept cookies" window when I visit mbasic.facebook.com in a fresh browser

Just delete the cookies and browser data from the chromium, after that (in my case) the accept cookie window will appear again

Edit: Even no success, if a start the chromium instance from Puppeteer folder and accept all cookies from [*.]mbasic.facebook.com  and [*.]facebook.com.

**Comment by opc241** [comment]
> , I'm not seeing the "accept cookies" window when I visit mbasic.facebook.com in a fresh browser

Just delete the cookies and browser data from the chromium, after that (in my case) the accept cookie window will appear again

**Comment by spieglt** [comment]
I just tried this again from a fresh Chromium instance and don't believe I'm getting the cookie pop-up. I wonder if it's a regional thing? I may need some detailed screenshots or for someone experiencing this to submit a PR.

**Comment by opc241** [comment]
Thanks for the hint with the regional thing! That's exactly it!. 
So as an solution (for me as a german):

-Connect VPN to United States

That's it. Greetings to DSGVO.

**Comment by spieglt** [comment]
Ganz gut, vielen Dank @opc241!

**Comment by spieglt** [comment]
Fixed by https://github.com/spieglt/fb-delete/commit/fb49b77e26d2f17efb1a27a1780c84df09217869

**Comment by maxiride** [comment]
I just downloaded the tool but I am getting the same issue that was mentioned as fixed here.

`Error: Error: failed to find element matching selector "input[id=m_login_email]"`

Video of the steps: https://streamable.com/46luw7

```
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: Error: failed to find element matching selector "input[id=m_login_email]"
    at ElementHandle.$eval (C:\Users\federicod\Downloads\fb-delete-master\node_modules\puppeteer\lib\JSHandle.
js:504:13)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:569:9)
    at process.processTimers (node:internal/timers:543:7)
    at async main (C:\Users\federicod\Downloads\fb-delete-master\index.js:35:3)
  -- ASYNC --
    at ElementHandle.<anonymous> (C:\Users\federicod\Downloads\fb-delete-master\node_modules\puppeteer\lib\hel
per.js:111:15)
    at DOMWorld.$eval (C:\Users\federicod\Downloads\fb-delete-master\node_modules\puppeteer\lib\DOMWorld.js:15
6:21)
    at async main (C:\Users\federicod\Downloads\fb-delete-master\index.js:35:3)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\federicod\Downloads\fb-delete-master\node_modules\puppeteer\lib\helper.js:1
11:15)
    at Page.$eval (C:\Users\federicod\Downloads\fb-delete-master\node_modules\puppeteer\lib\Page.js:345:29)   
    at Page.<anonymous> (C:\Users\federicod\Downloads\fb-delete-master\node_modules\puppeteer\lib\helper.js:11
2:23)
    at main (C:\Users\federicod\Downloads\fb-delete-master\index.js:35:14)

Node.js v24.7.0

C:\Users\federicod\Downloads\fb-delete-master>
```

**Comment by spieglt** [comment]
@maxiride I noticed it said "Accounts Centre" instead of the US spelling "Center": are you in the US? If not you may have to use a VPN to route your traffic through the US, or find what your region calls the `m_login_email` ID (and probably other IDs) and modify the code accordingly.
