### ISSUE TITLE
No matter what option I chose nothing works.

### ISSUE THREAD

**Issue by trent-wise** [spieglt/fb-delete#4]
```
(node:6988) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Invalid parameters url: string value expected
    at Promise (c:\Users\Trent\Desktop\fb-delete-master\node_modules\puppeteer\lib\Connection.js:198:56)
    at new Promise (<anonymous>)
    at CDPSession.send (c:\Users\Trent\Desktop\fb-delete-master\node_modules\puppeteer\lib\Connection.js:197:12)
    at navigate (c:\Users\Trent\Desktop\fb-delete-master\node_modules\puppeteer\lib\Page.js:520:39)
    at Page.goto (c:\Users\Trent\Desktop\fb-delete-master\node_modules\puppeteer\lib\Page.js:500:7)
    at followLinkByContent (c:\Users\Trent\Desktop\fb-delete-master\index.js:99:14)
    at <anonymous>
(node:6988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6988) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

That's the error message I get, it loads chronium, logs in fine then goes from my timeline to my profile and crashes... Any fixes?

**Comment by spieglt** [comment]
Hey, sorry for the delayed response. I don't know why I never got notifications about the issues for this repo but I'm just now seeing them. If it's getting to your profile but not your activity log, I'm afraid I'm not sure why. I've also deleted my Facebook account so am not able to troubleshoot at the moment.

**Comment by spieglt** [comment]
@trent-wise Apologies for the late notice but this should be fixed.
